name: Deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Setup Node.js
              uses: actions/setup-node@v4.0.1

            - name: Install dependencies
              run: npm install

            - name: Lint code
              run: npm run lint

            - name: Run tests
              run: npm run test

            - name: Upload coverage report to Codecov
              uses: codecov/codecov-action@v3.1.6
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
